### ISSUE TITLE
IWD EE installation (parsing error)

### ISSUE THREAD

**Issue by Stevenozzz** [Gibberlings3/Enhanced-Powergaming-Scripts#15]
Hello. Even though I'm installing the latest version, the scripts refuse to intall on IWD EE. I attached the debug file. I'm installing it as last in my mod order, should I change it?

Thank you
[SETUP-ENHANCED-POWERGAMING-SCRIPTS.zip](https://github.com/Gibberlings3/Enhanced-Powergaming-Scripts/files/9742775/SETUP-ENHANCED-POWERGAMING-SCRIPTS.zip)

**Comment by morpheus562** [comment]
On it! This should be easy to track down and get corrected here shortly.

**Comment by morpheus562** [comment]
I have a fix and should be able to release it tonight.

**Comment by Stevenozzz** [comment]
Damn youre fast

**Comment by morpheus562** [comment]
Newly released v10.2.2 should correct your issue. Thank you for your report!

**Comment by Stevenozzz** [comment]
Yep, works like a charm now.
