### ISSUE TITLE
12.1 is not working, characters are standing still (IA do nothing)

### ISSUE THREAD

**Issue by Mandallaz** [Gibberlings3/Enhanced-Powergaming-Scripts#19]
Using version 12.1, all my characters are standing still: the IA is doing nothing.
Installing back 11.2, every works perfectly.

What can I do to help you fix the issue?

**Comment by morpheus562** [comment]
Otherwise, there is a known bug with the SR version of the scripts if that is in your install order. The fix I have corrects the issue, so I am reviewing other sections prior to release.

**Comment by Mandallaz** [comment]
Hi!
Thanks for your answer. I already did the procedure from the documentation.
But because I had SR installed first, I am in the case of the known bug.
T

**Comment by morpheus562** [comment]
New v12.2 is released with the fix. Please let me know if you continue to have issues.

**Comment by morpheus562** [comment]
Did you completely uninstall the old script then install the new one? Please provide me a copy of you bddefai file.

**Comment by Mandallaz** [comment]
please find enclosed.
The last time I run the game, It was with 11.2.

T.

**Comment by Mandallaz** [comment]
Done on G3 forums (need moderator validation before you see it)
