### ISSUE TITLE
Hello author.  

### ISSUE THREAD

**Issue by daveymcman** [Gibberlings3/Enhanced-Powergaming-Scripts#20]
I have enjoyed this mod greatly but there are some issues which stump me.  I would like to mod this mod myself, but goodness it is a complicated beast

My issue is that I always play with multiple clerics and a sorcerer.

All my clerics cast the same prebuff spells ignoring the fact they they themselves have already cast it ( more than once ) as well as another cleric party member.  6 bless spells does not improve over one.

Also my sorcerer casts 5 blurs upon himself and simply casts the same spell until he has no spell levels left at a particular level.

Is there a way around this or could you even point me in the right direction of your tpa files - currently I am enjoying IWDEE but I play BGEE BG2EE endlessly

**Comment by morpheus562** [comment]
What version of my scripts are you using? I just tested Blur on my Sorcerer (IWDEE) and I had zero issues with duplicate casting.

**Comment by daveymcman** [comment]
Dear author -  I am using v10.2.5 and you are correct and I will confused about blur - but I am not confused about the cleric casting righteous magic 3 times in a row on themselves ( they had 3 memorised ) and the sorcerer does cast spell shield until they have no more level 5 spells to cast,   Also every cleric casts the same bless, prayer on the party etc

2nd, thank you so much for responding

**Comment by morpheus562** [comment]
I recommend installing the current scripts and then doing a fresh install of v12.4 to see if that improves the duplicate castings. I can do a bigger dive tomorrow if that doesn't correct the initial issue. 

Regarding multiple divine characters casting duplicates of the same spell: it really is not optimized to have more than a single divine caster within a party. This was actually part of my initial considerations creating these scripts a couple years ago and why I called them the "Powergaming" scripts. Parties shouldn't have more than a single, dedicated divine caster as anything more is unoptimal. With that said, these have evolved in the two years or so since I created the scripts. I have some ideas on how to address your concern, and all I can promise is "best effort" to implement a solution.

**Comment by daveymcman** [comment]
Dear author 

Thank you for your passion.  the scripts are fantastic and it is just incredible you took time to respond to my question.  the games are so old ( so am I actually ) you have every right to just get on with your life.  I unfortunately play IWDEE with a lot of mods including improved heart of fury mod which requires me to play 4 x FMC chars, 1 x FMT and 1 x sorcerer. because at least two of my clerics get knocked out in the first segment of must fights and I need at least one spamming heals just to survive.  

So I have downloaded the zip file from 
https://github.com/Gibberlings3/Enhanced-Powergaming-Scripts
and it has a package_mod.bat but normally I would just move the subfolder enhanced-powergaming-scripts into my game folder and run a bat or exe from there.  there does not appear to be a enhanced-powergaming-scripts.exe or a enhanced-powergaming-scripts.bat in the zip Could you please tell me what process I would use to install the mod from the ZIP

Thank you again for you patient and help

**Comment by morpheus562** [comment]
First uninstall the scripts via setup-enhanced-powergaming-scripts within your game folder. Then in GitHub, click on releases on the far right. Here you'll see version 12.4. Download and launch the .exe file then point to your game folder and install.

**Comment by daveymcman** [comment]
absolutely wonderful - I now know how to get mods from github ( did not know that before )  - will not bother you for a few days as I work through this, may even reinstall everything and start from scratch.

thank again for your assistance

**Comment by morpheus562** [comment]
Happy to help! Here is my repository of install logs, which includes my IWDEE log. Of note, I have some of my own mods that can add HLAs into IWDEE and allow for Bards to pick locks and detect/disarm traps. Definitely helps increase flexibility for party compositions.

**Comment by daveymcman** [comment]
bloody heck, my wife is not going to like you!  luckily I have been retired for 10 years so I spend literally 1000's of hours playing these games. will download nearly everything.

I wish you great success in all your endeavors.

**Comment by morpheus562** [comment]
Thank you, and same to you!
