### ISSUE TITLE
Ring of Gaxx error

### ISSUE THREAD

**Issue by basicals** [Gibberlings3/Enhanced-Powergaming-Scripts#22]
It seems the script is trying to cast Imp. Haste, but triggers the first ability which is Invisibility, and keeps spamming it since it doesn't find  Imp. Haste on the player.
This leads to the character going invisible midfight and not using Imp. haste at all.

Possibly because code is:
UseItem("RING39",Myself)  // Ring of Gaxx

![image](https://github.com/Gibberlings3/Enhanced-Powergaming-Scripts/assets/6373803/e138021d-5a70-4fff-9c34-6a343f49779f)

**Comment by morpheus562** [comment]
Fixed for next release.
