### ISSUE TITLE
Shield of the Archons being cast for the last

### ISSUE THREAD

**Issue by basicals** [Gibberlings3/Enhanced-Powergaming-Scripts#24]
Shouldn't it be cast mostly first of all? Since it's duration is 3 rounds / level, much higher than most priest buffs.

![image](https://github.com/Gibberlings3/Enhanced-Powergaming-Scripts/assets/6373803/0338499d-e62b-48e2-8f19-231253f277d2)

The rest of the spells are cast properly in order of duration,

Cheers,

**Comment by morpheus562** [comment]
I don't want the Cleric to block friendly buff spells with this one. It is put last to maximize the amount of buffs the cleric receives and reduce any chance of weakening the shield.

**Comment by basicals** [comment]
Aaah yes, targeted buffs won't get through. Sorry it's pretty late here.

Thanks,

**Comment by morpheus562** [comment]
No worries and good questions. I appreciate the feedback and a second set of eyes.
