### ISSUE TITLE
Both Fireshields shouldn't be exclusive

### ISSUE THREAD

**Issue by basicals** [Gibberlings3/Enhanced-Powergaming-Scripts#25]
They can be stacked for 50% fire and cold resistance and fire plus cold damage to attackers. Shouldn't be a reason to have them check for each other exclusively.

Cheers,

**Comment by morpheus562** [comment]
I prefer keeping them staggered as it increases the number of times I can buff while in a dungeon. Putting both up is just overkill when one is sufficient.

**Comment by basicals** [comment]
I read you, but for that effect wouldn't you have more than one copy of the _same_ color learned, instead one of each? 
Makes sense to be allowed to have both different damages and resistances simultaneous if you learn scribe one of each.

Cheers,
