### ISSUE TITLE
Ring of Gaxx: Redux

### ISSUE THREAD

**Issue by basicals** [Gibberlings3/Enhanced-Powergaming-Scripts#26]
Hi,
I've played around with the ring of gaxx haste effect and noticed it's checking for conditions it shouldn't:

![image](https://github.com/Gibberlings3/Enhanced-Powergaming-Scripts/assets/6373803/d5e94f3f-6495-4549-bb0b-f08fdfe56c09)

After testing it, i can report that since it's an item spell, it can be cast without failure under miscast magic, insect plague, poison, silence, wild magic areas and dead magic areas.

Also, and maybe a longshot, is it possible to check for the spell duration and adjust the cooldown on the script? Since forgotten armaments increase it to 5 rounds, from 10 seconds. Otherwise, the script will spend three charges unnecesarly.

Cheers,

**Comment by morpheus562** [comment]
Where are you seeing a cool down for it? I'm checking if the spell state is present.

**Comment by basicals** [comment]
Weird, here's Jaheira attempting to use the ring at about 10 seconds after the first use, while IH is still going (5 rounds).
![image](https://github.com/Gibberlings3/Enhanced-Powergaming-Scripts/assets/6373803/5d24197b-a910-4cc5-b1b4-cffd2ac0315b)

Here's the resulting stack of three casts of ring of gaxx.
![image](https://github.com/Gibberlings3/Enhanced-Powergaming-Scripts/assets/6373803/61af5cd8-7601-4da8-aca1-f4274c510d61)
![image](https://github.com/Gibberlings3/Enhanced-Powergaming-Scripts/assets/6373803/b741ac28-0807-4cf9-b1a9-e159626627c4)

Here's normal IH on Jan.
![image](https://github.com/Gibberlings3/Enhanced-Powergaming-Scripts/assets/6373803/c09356a4-4ce6-48fd-8039-307b34ac6dd0)

Here's IH from cheetah amulet.
![image](https://github.com/Gibberlings3/Enhanced-Powergaming-Scripts/assets/6373803/2668d387-e566-4950-b275-6765082e771d)
![image](https://github.com/Gibberlings3/Enhanced-Powergaming-Scripts/assets/6373803/bf7ddc42-2e2e-4981-8cb6-1d9d8440b71d)

Right, so the cheetah script will also cast on top of a ring of gaxx, but not on top of a normal or cheeth amulet IH. I suspect Gaxx ring improved haste is not being accounted as improved_haste spell state since it doesn't actually cast spell 146 but applies a haste effect?.

Oh and about the ring of gaxx script checks (spell failure, poisoned etc); these don't correspond here since this ring effect is not casting both haste or invisibility, rather applying the effects directly, so they work naturally under any of the checked conditions.

**Comment by basicals** [comment]
Ahhh yes,

Ring of gaxx haste effect doesn't include applying improved_haste effect:

![image](https://github.com/Gibberlings3/Enhanced-Powergaming-Scripts/assets/6373803/cc195694-6efd-4f9e-896c-05b93b5b7a61)

**Comment by morpheus562** [comment]
That is the correct opcode for IH. Look at Haste Type and it will correctly show as improved.

**Comment by basicals** [comment]
Yes it is, but as I understand it, your script is checking for spell state 196 IMPOVED_HASTE".
Which ring of gaxx does not set.

You can see how the mage's IH does apply this spell state, so your script works with it, but not with the ring of gaxx:

Normal IH
![image](https://github.com/Gibberlings3/Enhanced-Powergaming-Scripts/assets/6373803/f2f15067-0949-48b8-9ead-d7243b03a5d5)
![image](https://github.com/Gibberlings3/Enhanced-Powergaming-Scripts/assets/6373803/0f0a7c9a-b6bb-4eaf-b653-01368ba5b45d)

**Comment by morpheus562** [comment]
I see SCS is doing some stuff with IH, so I need to see how it interacts with this ring. I plan to get it resolved in my next release.

**Comment by morpheus562** [comment]
Fixed in release v12.6.
