### ISSUE TITLE
Script cancels user command in favor of scripted behavior

### ISSUE THREAD

**Issue by comiluv** [Gibberlings3/Enhanced-Powergaming-Scripts#28]
# Description
When a character is issued to cast "Deathblow" HLA while casting scripted "Draw Upon Holy Might", the script blocks casting of "Deathblow" spell and continues to cast "Draw Upon Holy Might"

# Steps to reproduce the issue
1. Start a new game with pregenerated Abdel character
2. Give Abdel 3 million xp `C:SetCurrentXP(3000000)`
3. Level up Abdel and give him "Deathblow" HLA
4. Summon a golem at cursor position `C:CreateCreature("golada01")`
5. Observe the script casts "Draw Upon Holy Might" automatically
6. In the middle of casting, pause the game and cast "Deathblow" HLA
7. See error

# What happens
The script cancels player issued "Deathblow" command and instead casts "Draw Upon Holy Might"

# What's expected to happen
The character casts "Deathblow" without the script cancelling player issued command

# Screenshot
https://github.com/Gibberlings3/Enhanced-Powergaming-Scripts/assets/19642705/e30c360c-1ec6-4764-9af1-7ad49f2594f5

# Additional info
Baldur's Gate 2 EE version 2.6.6.0
Enhanced Powergaming Scripts v12.7

This issue doesn't seem to be limited to situations where the script tries to cast DUHM or the user tries to issue Deathblow. I've seen the script cancelling user issued Greater Whirlwind in favor of casting Improved Haste from Gaxx ring, etc. in my current playthrough.

# weidu.log
```
// Log of Currently Installed WeiDU Mods
// The top of the file is the 'oldest' mod
// ~TP2_File~ #language_number #component_number // [Subcomponent Name -> ] Component Name [ : Version]
~ENHANCED-POWERGAMING-SCRIPTS/ENHANCED-POWERGAMING-SCRIPTS.TP2~ #0 #15 // Install Enhanced Powergaming Scripts -> Accelerated Pre-Buffing Speed: v12.7
~ENHANCED-POWERGAMING-SCRIPTS/ENHANCED-POWERGAMING-SCRIPTS.TP2~ #0 #9 // Install Enhanced Scripts for Summoned Celestials: v12.7
~ENHANCED-POWERGAMING-SCRIPTS/ENHANCED-POWERGAMING-SCRIPTS.TP2~ #0 #10 // Install Enhanced Scripts for Simulacrum: v12.7
```

**Comment by morpheus562** [comment]
Try with EEex as that allows more control on preventing overwriting player actions.

**Comment by comiluv** [comment]
Installed EEEx v0.10.2-alpha but the issue persists.
Video of the issue:
https://github.com/Gibberlings3/Enhanced-Powergaming-Scripts/assets/19642705/e386684a-00df-46d7-8229-e064864c3b9e

weidu.log:
```
// Log of Currently Installed WeiDU Mods
// The top of the file is the 'oldest' mod
// ~TP2_File~ #language_number #component_number // [Subcomponent Name -> ] Component Name [ : Version]
~EEEX/EEEX.TP2~ #0 #0 // EEex: v0.10.2-alpha
~EEEX/EEEX.TP2~ #0 #1 // Experimental - Use LuaJIT (can help stuttering): v0.10.2-alpha
~EEEX/EEEX.TP2~ #0 #2 // Enable effect menu module - LShift-on-hover to view spells affecting creature: v0.10.2-alpha
~EEEX/EEEX.TP2~ #0 #3 // Enable empty container module - Highlight empty containers in gray instead of cyan: v0.10.2-alpha
~EEEX/EEEX.TP2~ #0 #4 // Enable timer module - Visual indicators for modal actions, contingencies, and spell/item cooldowns: v0.10.2-alpha
~EEEX/EEEX.TP2~ #0 #5 // Timer module - Show modal actions (red bar): v0.10.2-alpha
~EEEX/EEEX.TP2~ #0 #6 // Timer module - Show contingencies (green bar): v0.10.2-alpha
~EEEX/EEEX.TP2~ #0 #7 // Timer module - Show spell/item cooldowns (cyan bar): v0.10.2-alpha
~EEEX/EEEX.TP2~ #0 #8 // Enable time step module - Advance 1 game tick on keypress: v0.10.2-alpha
~EEEX/EEEX.TP2~ #0 #9 // Enable hotkey module - Edit override/B3Hotkey.lua to create advanced spell hotkeys: v0.10.2-alpha
~ENHANCED-POWERGAMING-SCRIPTS/ENHANCED-POWERGAMING-SCRIPTS.TP2~ #0 #15 // Install Enhanced Powergaming Scripts -> Accelerated Pre-Buffing Speed: v12.7
~ENHANCED-POWERGAMING-SCRIPTS/ENHANCED-POWERGAMING-SCRIPTS.TP2~ #0 #9 // Install Enhanced Scripts for Summoned Celestials: v12.7
~ENHANCED-POWERGAMING-SCRIPTS/ENHANCED-POWERGAMING-SCRIPTS.TP2~ #0 #10 // Install Enhanced Scripts for Simulacrum: v12.7
```

**Comment by morpheus562** [comment]
Hmm. That looks like a timing issue. You cancel out DUHM mid-cast. Can you let it complete casting of it and then attempt Deathblow right after?

**Comment by comiluv** [comment]
I'm not sure I understood your comment correctly. The issue is that the player doesn't want to cast DUHM and wants to instead cast Deathblow.

**Comment by comiluv** [comment]
Anyway, I tried what you suggested: I let the script cast DUHM fully and tried casting Deathblow right after. The script cancelled the Deathblow.

**Comment by morpheus562** [comment]
Are you on discord or something else I can send you an updated file to test?

**Comment by comiluv** [comment]
I'll send you a message in G3 discord

**Comment by morpheus562** [comment]
Item causing it is identified and is corrected in a pre-release version. I'm looking at alternatives to do what I was trying to do without interrupting the player actions.

**Comment by morpheus562** [comment]
Corrected in the new release
