### ISSUE TITLE
Script spends too much rounds buffing

### ISSUE THREAD

**Issue by comiluv** [Gibberlings3/Enhanced-Powergaming-Scripts#29]
# Description
This is a script improvement suggestion and not related to any bug.
Script spends too much rounds buffing with "Use Items" turned on, so would like an option to limit this behavior

# How it works now
I'm currently playing ToB with Ehanced Powergaming Scripts.
My playstyle using the script is to simply press "N" before entering a dungeon, and to press "B" before big fights, and manually controlling everything in battle.
To suit the script around my playstyle, I only checked "Attack Enemies", "Group Buffing", "Use Items", "Enemy Debuffing/Curative/Healing". I kept "Use Items" to automatically cast Spell Trap from Staff of Magi, Stoneskin from Gargoyle Boots, Set constitution to 18 from Girdle of Fortitude for convenience.
What I noticed recently is with `Use Items` checked, the script spends too much time in the beginning of a fight buffing, which could result in inefficient spell allocation for the fight.
For example in my last fight in Sendai's Enclave, for first few rounds the script used Headband of the Devout, Gargoyle Boots, Ring of Gaxx, spending first 2~3 rounds while the enemies attacked the party. Some of the party characters had Greater Whirlwind casted beforehand which was wasted, too.

# How the script could be improved
I would like to have an option to set the script not cast buff spells in the battle but only for precasting buffs before battle or long-lasting daily buffs.
For example players could use the script better if the script would cast Stoneskin from items or their spellbook after every rest for buffing, or buff hotkey is pressed, but not when in combat, and instead cast damaging spells and abilities in combat.

# Additional info
version 13.0 cloned from github

**Comment by morpheus562** [comment]
Uncheck "Use Defensive Spells" should do the trick for you.
