### ISSUE TITLE
Indication on install order for multi-mod install

### ISSUE THREAD

**Issue by mleduque** [Gibberlings3/Enhanced-Powergaming-Scripts#4]
Hi,
I feel like the readme is missing just a little bit on information on when this module is better installed.
I found on the discussion thread the following cmoment
> Just note that this mod needs to be installed at the end of your installation order so it can detect the other mods that may impact the scripts. 
That would probably be enough for nearly all cases I think?

Before that, I had looked at the scripts and I could be more precise and say
- after item revisions (if installing any of the "restore item" componnents)
- after spell revisions, stratagems, iwdification, tome and blood, song and silence, faiths and powers
but that's just tounderstand better myself and the readme would maybe not need to be this precise.

**Comment by morpheus562** [comment]
Thank you for the feedback! I have gone ahead and updated the readme which should resolve your comment. If using PI, it should be properly identified which mods need to be installed before the scripts, too!
