### ISSUE TITLE
Case Sensitivity Issue

### ISSUE THREAD

**Issue by yuyuanshuo** [Gibberlings3/Enhanced-Powergaming-Scripts#5]
There are both a folder called BGEE and another called bgee within ./lib/

**Comment by morpheus562** [comment]
I am not sure which folders you are referencing. Within the ./lib/ folder there is a folder titled "bg2ee" and another "bgee" to differentiate differences between those different games. Is this what you are seeing? What specific errors are you encountering or is this just a matter of semantics?

**Comment by morpheus562** [comment]
The issue has been corrected and is now showing as one bgee folder.

**Comment by yuyuanshuo** [comment]
> Thank you, I see what you are saying. There seems to be an issue with github.com where it is not consolidating those two folders into a single bgee folder; however, I can assure you they are both within the same bgee folder in the install. I will dig into what is causing this, but you should not experience any issues with the mod as a result of it.

Probably because Github is case-sensitive by default...did you happen to have two computers with each having a copy of the project, and on one computer you have a BGEE folder while on the other computer you have a bgee folder instead? Or maybe you have a separate branch that has either bgee or BGEE while the master branch has the other one? I don't know...

Btw, I am guyudennis at Gibberlings3. I hope you solved your EET kit description issue. :-)
